# Site
name: "Souhail"
title: "Affiliates Theme for Jekyll"
description: "Jekyll Theme for Blogging"
meta_description: "Jekyll theme for blogging."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'somaisouhail0@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  souhail :
    name: Souhail Somai
    display_name: Souhail Somai
    gravatar: 4c9ab95419bdb6335577922888fa0688
    email: somaisouhail0@gmail.com
    web: http://souhails.me
    twitter: https://twitter.com/souhail_somai
    description: "I'm knowledge seeker. Entrepreneur. Marketing enthusiast aswell as a Tech Geek."
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
souhail-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
