lang: en
title: Souhails
author: souhail
email: somaisouhail0@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Digital marketing, Entrepreneurship you'r daily dose of knowledge.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://souhails.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: souhail_somai
logo: /assets/icons/android-chrome-512x512.png
social:
  name: Souhail Somai
  links:
    - https://twitter.com/ymatuhin
    - https://instagram.com/bazol.co
    
    

# Build settings
safe: true
paginate: 10
paginate_path: "/page:num/"

permalinks: pretty
permalink: /:categories/:title/
sass:
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap # https://github.com/jekyll/jekyll-sitemap
  - jekyll-seo-tag # https://github.com/jekyll/jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

