# Site
name: "Souhails"
title: "Making Entrepreneurship and Marketing Easy. "
description: "Easy Entrepreneurship, Marketing and Tech guides for everyone."
meta_description: "Hub for Entrepreneurship, Marketing and Tech"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'somaisouhail0@gmail.com'
google_analytics: 'G-NPMYC0V77X'
disqus: 'souhails'
sharethis: '<script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=6015f09ba251a600196293b4&product=sticky-share-buttons" async="async"></script>'

# Authors
authors:
  souhail:
    name: Souhail 
    display_name: Souhail Somai
    gravatar: 4c9ab95419bdb6335577922888fa0688
    email: somaisouhail0@gmail.com
    web: http://souhails.me
    twitter: https://twitter.com/souhail_somai
    description: "I'm a knowledge seeker. Entrepreneur. Marketing enthusiast aswell as a Tech Geek."
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
souhail-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
